### ISSUE TITLE
Typo in generated Ghidra script

### ISSUE THREAD

**Issue by BlueAmulet** [LukeFZ/Il2CppInspectorRedux#3]
In commit 55532fdc8af5e3f86ff3f2a25695f0aea3e123fd, the generated Ghidra script has a class called `StatusWrapper`, but the IDA script and extra code added afterwards creates an object of type `StatusHandler`

Changing the class name to StatusHandler gets the script working again.

**Comment by LukeFZ** [comment]
my bad - pushed a fix for it!
